name: render
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 4 * * *"

jobs:
  all:
    name: Render cheat sheets
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CHROMOTE_CHROME_ARGS: "--no-sandbox"

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Prepare daily timestamp for cache
        id: date
        run: echo "date=$(date '+%d-%m')" >> "$GITHUB_OUTPUT"

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: cheatsheets-${{ steps.date.outputs.date }}
          restore-keys: cheatsheets-

      - name: Install system dependencies
        run: sudo apt-get install -y libcurl4-openssl-dev libgit2-dev

      - name: Install dependencies
        run: |
          Rscript -e "install.packages('pak', repos = sprintf('https://r-lib.github.io/p/pak/stable/%s/%s/%s', .Platform[['pkgType']], R.Version()[['os']], R.Version()[['arch']]))"
          Rscript -e "pak::local_install_deps(dependencies = TRUE)"

      - name: Render cheat sheets
        run: |
          Rscript -e "cheatdown::print_pdf('mlr3/mlr3.Rmd', 'pdf/mlr3.pdf')"
          Rscript -e "cheatdown::print_pdf('mlr3tuning/mlr3tuning.Rmd', 'pdf/mlr3tuning.pdf')"
          Rscript -e "cheatdown::print_pdf('mlr3fselect/mlr3fselect.Rmd', 'pdf/mlr3fselect.pdf')"
          Rscript -e "cheatdown::print_pdf('mlr3pipelines/mlr3pipelines.Rmd', 'pdf/mlr3pipelines.pdf')"

      - name: Deploy
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: pdf/
          clean: false

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cheatsheet
          path: |
            pdf/
            mlr3/
            mlr3tuning/
            mlr3fselect/
            mlr3pipelines/
